apiVersion: v1
kind: Pod
metadata:
  name: pvc-demo
spec: 
  containers:
  - name: app-container
    image: nginx
    volumeMounts: 
    - mountPath: "/usr/share/nginx/html"
      name: example-storage
  volumes: 
  - name: example-storage
    persistentVolumeClaim:
      claimName: example-pvc
