stages:
  - build
  - test
  - deploy

build-job:
  stage: build 
  script:
    - echo "Building the Application"

test-job:
  stage: test 
  script:
    - echo "Testing the Application"
    - exit 0

deploy-job:
  stage: deploy 
  script:
    - echo "Deploying the Application"
    - exit 0