apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: "redis"
  replicas: 3
  selector:
    matchLabels:
      app: redis 
  template:
    metadata:
      labels: 
        app: redis 
    spec: 
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379

---

apiVersion: v1 
kind: Service 
metadata:
  name: redis 
spec: 
  selector:
    app: redis
  clusterIP: None 
  ports:
    - port: 6379