apiVersion: v1
kind: Pod
metadata:
  name: affinity-demo
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - matchExpressions:
          - key: disktype
            operators: In
            values:
              - ssd
  containers:
    - name: app-container
      image: nginx

# RequiredDuringSchedulingIgnoredDuringExecution: Pod must run on a matching node.
# PreferredDuringSchedulingIgnoredDuringExecution: Scheduler attempts to place Pod on a preferred node but can still run elsewhere if no match is found.
