apiVersion: v1
kind: Pod
metadata:
  name: affinity-demo
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - matchExpressions:
          - key: disktype
            operators: In
            values:
              - ssd
  containers:
    - name: app-container
      image: nginx
